### ISSUE TITLE
0dbfs not taken into account generating csd to screen

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/blue#286] opened 2014-08-27 18:15 UTC
Generating csd to the screen always shows 0dbfs=1, even if it's disabled or another value is put in.

The generated .csd seems correct, and generating realtime .csd to screen seems correct.

**Comment by kunstmusik** [comment] 2015-01-21 04:39
I'm unable to reproduce this with the latest in the develop branch (which will be the upcoming 2.6.0 release).  Closing this ticket out.

**Closed by kunstmusik** 2015-01-21 04:39 UTC
