### ISSUE TITLE
Single Mode refuses to delete or copy AL points

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#423] opened 2019-01-29 11:04 UTC
When starting up an existing project and wanting to, in Single Mode, select and delete or copy the AL points in the marquee, i find it is not possible to do so.
Going to Multi Mode and selecting some ALs and points do work, then going back to Single Mode and wanting to delete or copy/paste, all works well.

**Comment by tjingboem** [comment] 2019-02-07 07:49
Sometimes it is impossible to even create a marquee in Single Mode
![screenshot from 2019-02-07 08-48-02](https://user-images.githubusercontent.com/6670911/52397318-49f8cc80-2ab5-11e9-91bf-3dec3a3cc149.png)

**Comment by pjw6900** [comment] 2019-02-07 11:28
This sounds related to #411. I'll try to reproduce the behavior here to figure out the cause.

**Comment by kunstmusik** [comment] 2019-02-07 11:29
This sounds related to #411. I'll try to reproduce the behavior here to figure out the cause.

**Comment by kunstmusik** [comment] 2019-02-07 11:32
@tjingboem Question: Is this using audio layers? I wonder if that could be a factor (vs. the testing/work done in #411 which I believe I did using SoundObject layers)

**Comment by tjingboem** [comment] 2019-02-07 12:16
yes, you are right in that the marquee refuses to be created on the AudioLayer

**Comment by kunstmusik** [comment] 2019-02-07 12:17
Thanks for checking, that narrows what I need to look into now.

**Comment by kunstmusik** [comment] 2019-02-07 12:20
Okay, this looks straightforward, I think I never updated some code in AudioLayers when I did changes in SoundObject layers. Fingers crossed... :)

**Comment by tjingboem** [comment] 2019-02-07 12:21
once the thing with the AudioLayers is corrected, i can focus better on what's going on with selecting and copying on the SoundObject Layer

**Comment by kunstmusik** [comment] 2019-02-07 12:36
@tjingboem Could you test https://kunstmusik.com/blue_2.7.4_dev.zip ?

**Comment by kunstmusik** [comment] 2019-03-10 01:51
I'm assuming this is fixed so I will close this issue. Please let me know if there are any further issues.

**Closed by kunstmusik** 2019-03-10 01:51 UTC
