### ISSUE TITLE
macOS strange behaviour with Score Objects

### ISSUE THREAD

**Issue by boonier** [kunstmusik/blue#758] opened 2023-09-05 09:03 UTC
Observed v2.9.0 on M1 Mac Monterey.

I'm getting some odd behaviour like grouping of score objects, and occasionally one duplicating on top another:

https://github.com/kunstmusik/blue/assets/6206789/1d91fef2-3ea0-485b-ae8c-53cca8ca07a3

I'm not sure, but I wasn't aware there was a feature to group adjacent sound objects...unless there is?

thanks

**Comment by kunstmusik** [comment] 2023-09-05 12:27
This definitely looks like a bug, could you send a .blue project file for me to test and see if I can reproduce?

**Comment by boonier** [comment] 2023-09-05 15:01
Sure thing, thanks

[gen fm.blue.zip](https://github.com/kunstmusik/blue/files/12525116/gen.fm.blue.zip)

**Comment by kunstmusik** [comment] 2023-09-07 03:09
I can reproduce the issue here. I think I might know why it's happening but I need to do some sleuthing through git history to verify. Will report back once I have the root cause sorted out and have a fix.

**Comment by kunstmusik** [comment] 2023-09-09 19:49
@boonier I think I have a fix. The issue stems from overriding the equals() method and looks like it affected JMask, ObjectBuilder, and Tracker objects. I think the change I did was safe but am continuing to test. You can find a build here:

https://github.com/kunstmusik/blue/actions/runs/6132818214

(artfacts near the bottom of the page). 

My testing here has fixed up the issue with the selection quirks with your test project.  If you could give this a try and confirm the fix, I'll release a 2.9.1 hotfix release.

**Comment by boonier** [comment] 2023-09-10 16:07
@kunstmusik confirmed that is working properly for me now. Thanks for looking into this!

**Comment by kunstmusik** [comment] 2023-09-10 17:25
Thanks @boonier for confirming! I will put together a hotfix 2.9.1 release later today. Closing out this issue.

**Closed by kunstmusik** 2023-09-10 17:25 UTC
