### ISSUE TITLE
Jack in not found

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue#305] opened 2015-04-14 09:04 UTC
in Options, realtime render, the Jack Audio In driver not found - but i can set it manually

the Jack out is found

**Comment by kunstmusik** [comment] 2016-07-28 00:17
I am unable to reproduce this with 2.6.0-test11.  Does this problem still exist for you @tjingboem ?

**Comment by tjingboem** [comment] 2016-07-28 07:38
Yes, it does.
The Jack Out is being detected just fine, not so the Jack In. When I click the detection button it shows the  Jack Out playback, not the Jack In capture.

here is a screenshot after clicking the Jack In detection button:
![screenshot from 2016-07-28 09 33 56](https://cloud.githubusercontent.com/assets/6670911/17204620/d25838dc-54a6-11e6-9479-0c88f6cd2efa.png)

I found a solution by manually editing the Jack In:
![screenshot from 2016-07-28 09 32 57](https://cloud.githubusercontent.com/assets/6670911/17204639/f0509f8c-54a6-11e6-844c-33cd93329f90.png)

**Comment by kunstmusik** [comment] 2016-07-28 15:59
Ah, I see what is going on.  So the issue is that the Jack detection code was modified in 2.4.1 to try to parse Csound's output and, if failing, resort to using jack_lsp.  I think on my system, the code works for using Csound on output, but not for input, which then falls back to jack_lsp.  When I looked at jack_lsp, I saw that code had the detection flipped: it read "input" as something to read from and "output" as something to write to, which is the opposite. I have fixed that in the jack_lsp related code and it will be in the next release.

**Closed** 2016-07-28 16:01 UTC
Labels: bug
