### ISSUE TITLE
Some example files crash when played

### ISSUE THREAD

**Issue by jxmc** [kunstmusik/blue#328] opened 2016-08-08 19:34 UTC
For example, when I played part one of Stephen Yi's etude, Blue crashed and created a temp file.  I wonder why a few example pieces crash when played?  Another example is that when Brian Wong's Slendronica#1 was played, it was all "choppy" and stuff.  Is it supposed to play like that?

**Comment by kunstmusik** [comment] 2016-08-08 21:25
I think I would need more information to diagnose.  For Slendronica, you may want to check the realtime render settings and adjust the ksmps value.  For the other crashes, could you note:

1. What version of Blue?
2. What Operating System are you using?
3. What version of Csound do you have installed?

**Comment by jxmc** [comment] 2016-08-09 18:57
I am using the latest version of Blue and the latest version of CSound.  I am using Windows 10.  Maybe I should try your suggestion first, which I can find in the manual.  I am actually very new to CSound and Blue, which is why I was listening to the example files

**Comment by kunstmusik** [comment] 2016-08-09 22:38
Is this 6.07 for Windows?  If so, are you using the blue64.exe to start the program?  This will be necessary as the 6.07 that was released is x86_64 64-bit and the executable used to start Blue needs to match, and blue64.exe is only provided with Blue 2.6.0.  If you want to use an older Blue, you can also try disabling the use of the Csound API, which will then call Csound in a separate process (but loses some realtime features that requires using the API).  If there are specific files that crash, just mention them here and I can try to reproduce the problem locally.

**Comment by kunstmusik** [comment] 2016-08-22 12:55
@jxmc I'm going through the Blue issues list today and thought I'd see where this issue stands.  Could you reply if the issues occur with 2.6.0?

**Comment by jxmc** [comment] 2016-08-25 02:04
I am talking about 2.6.0.  Unfortunately, I am not working on Blue for now.  Instead, I am experimenting with different free analog softsynths and chiptune trackers.  I don't even know if I will ever compose music with Blue.  I am satisfied with what I have now

**Comment by tjingboem** [comment] 2016-08-25 06:37
I hope i am not intruding, but i'd like to mention that this is happening in Linux/Jack as well.
Steven Yi's Etude simply crashes Blue and Brian Wong's Slendronica#1 sometimes has a choppy sound.  The latter is due to Xruns on my system, and probably has to to with my system not keeping up with the poor speed of Python's note generation - rendering the piece to disk produced a clean sound. (The "Process On Load" option did not help either in realtime)

**Comment by kunstmusik** [comment] 2016-08-25 11:12
@jxmc Thanks, I got confused as to what version you were using as you mentioned "I have encountered this problem in the second to latest version from 2014."  Etude part1 operates correctly here and I am also on Windows 10, which means this may take some time to diagnose as I will have to reproduce the crash somehow. Otherwise, I'm always happy to hear when people find a setup that works for them.  Hopefully if you revisit Blue in the future you'll find these issues sorted out. 

@tjingboem : for the crashing with Etude, are you using Csound 6.07 or latest from the develop branch?  Maybe I will have better luck reproducing the issue on Linux or OSX, which I will try later today. 

As for Slendronica, I checked and the reason it is choppy is not ksmps as I had first thought. It's also not that it uses python, as the score generation happens all before realtime rendering begins.  The reason it has issues is that Brian uses an approach to Csound instrument design that uses 100's of pfields.  I think the chop happens on the initialization of each note. I don't think instruments with very large number of pfields is one that Csound is optimized for.  The issue presents itself even if you render the project to a CSD, close Blue, and render the CSD with Csound alone.  If anything is to be done for this piece, it will have to be done within Csound itself.  

I'll email the Csound-dev list to see if anyone has time to profile Csound and diagnose the issue with events with 100+ pfields.  For Etude I'll see if I can reproduce the crash on other systems.

**Comment by kunstmusik** [comment] 2016-08-25 12:43
Update: I tested on Linux and got a crash with Etude part 1. The crash happens in Csound and is not an issue with Blue, as the crash is reproducible when generated a CSD file and running Csound on the CSD.  This occurred using a build of Csound from July 11th, which would make me think that the problem also would occur with the 6.07 release.  

I built Csound with the latest from the develop branch and it does not crash.  My diagnosis of this issue is that the root cause lies in Csound but it has already been addressed in recent Csound code changes.  Users not building Csound will need to compile Csound themselves, wait until 6.08, or ask for a developer build of Csound (I can provide relevant files on Windows and OSX and directions on how to patch the install).  The issue with Slendronica is also one with Csound itself and is being looked into within Csound. 

Although the issues are happening when using Blue, there's nothing Blue-specific about these issues that I can do anything from Blue's code.  I will close out this issue now.

**Closed by kunstmusik** 2016-08-25 12:43 UTC
